#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Testapplicatie.Resource", IsApplication=true)]

namespace Testapplicatie
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int LocationName = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int buttonVraag1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int buttonVraag2 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int buttonVraag3 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int buttonVraag4 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int buttonVraag5 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int buttonVraag6 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int buttonVraag7 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int buttonVraag8 = 2131099655;
			
			// aapt resource value: 0x7f06000e
			public const int map = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int plotView = 2131099656;
			
			// aapt resource value: 0x7f06000f
			public const int plotView2 = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int returnButton = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int saveLocation = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int showLocationOnMap = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int spinner = 2131099661;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int One_View = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Question1 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Two_Views = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Database = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int returnLabel = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int selectBike = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int us_1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int us_2 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int us_3 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int us_4 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int us_5 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int us_6 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int us_7 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int us_8 = 2131034121;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
